/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Returns the version string of the native zero-edge core module. */
export declare function version(): string
/**
 * Formats a transport error message through the shared core error model.
 *
 * This exists to prove the native core is linked and callable from Node: it
 * constructs a core [`Error`] from a JavaScript string and returns its rendered
 * form.
 */
export declare function formatTransportError(message: string): string
