/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Returns the version of the native zero-edge module. */
export declare function version(): string
/** MQTT delivery guarantee, mirroring the protocol's quality-of-service levels. */
export const enum Qos {
  /** Fire and forget; the broker does not acknowledge delivery. */
  AtMostOnce = 'AtMostOnce',
  /** Delivered at least once and acknowledged. */
  AtLeastOnce = 'AtLeastOnce',
  /** Delivered exactly once via a four-step handshake. */
  ExactlyOnce = 'ExactlyOnce'
}
/** Connection settings for an [`MqttClient`]. */
export interface MqttClientOptions {
  /** The MQTT client identifier presented to the broker. */
  clientId: string
  /** The broker hostname or IP address. */
  host: string
  /** The broker TCP port, conventionally 1883 for plaintext MQTT. */
  port: number
  /** Keep-alive interval in seconds. Defaults to 30 when omitted. */
  keepAliveSecs?: number
  /** Bound on outstanding client requests. Defaults to 64 when omitted. */
  capacity?: number
  /** Default quality of service. Defaults to `AtLeastOnce` when omitted. */
  qos?: Qos
}
/** A message received from a subscribed topic. */
export interface MqttMessage {
  /** The topic the message was published to. */
  topic: string
  /** The raw payload bytes. */
  payload: Buffer
}
/** An MQTT client transport backed by the native zero-edge core. */
export declare class MqttClient {
  /** Creates a disconnected client from the given options. */
  constructor(options: MqttClientOptions)
  /** Connects to the broker and starts the background event loop. */
  connect(): Promise<void>
  /** Publishes a payload to a topic. */
  publish(topic: string, payload: Buffer): Promise<void>
  /** Subscribes to a topic filter. */
  subscribe(topic: string): Promise<void>
  /**
   * Awaits the next message from any subscribed topic, or `null` once the
   * connection has ended.
   */
  recv(): Promise<MqttMessage | null>
  /** Reports whether the client currently holds an active connection. */
  isConnected(): Promise<boolean>
  /** Closes the connection and stops the background event loop. */
  disconnect(): Promise<void>
}
